return {
    "yorik1984/newpaper.nvim",
    opts = {
	style               = "light",
	lightness           = 0,
	saturation          = 0,
	greyscale           = false,
	editor_better_view  = true,
	terminal            = "contrast",
	sidebars_contrast   = {},
	contrast_float      = true,
	contrast_telescope  = true,
	operators_bold      = true,
	delimiters_bold     = false,
	brackets_bold       = false,
	delim_rainbow_bold  = false,
	booleans            = "bold",
	keywords            = "bold",
	regex               = "bold",
	regex_bg            = true,
	tags                = "bold",
	tags_brackets_bold  = true,
	tex_major           = "bold",
	tex_operators_bold  = true,
	tex_brackets_bold   = false,
	tex_math_delim_bold = false,
	tex_keywords        = "NONE",
	tex_zone            = "italic",
	tex_arg             = "italic",
	error_highlight     = "undercurl",
	italic_strings      = false,
	italic_comments     = true,
	italic_doc_comments = true,
	italic_functions    = false,
	italic_variables    = false,
	borders             = true,
	disable_background  = false,
	lsp_virtual_text_bg = true,
	hide_eob            = false,
	colors              = {},
	colors_advanced     = {
	},
	custom_highlights   = {
	    ["@none"] = { fg = "#2A2A2A" }
	},
	lualine_bold        = true,
	lualine_style       = "light",
    }
}
